services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb-instance
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=secret
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - ./import:/import
    restart: unless-stopped

volumes:
  arangodb_data: