services:
  arangodb:
    image: arangodb
    container_name: arangodb-instance
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=
    restart: unless-stopped

  neo4j:
    image: neo4j
    container_name: neo4j-instance
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

volumes:
  neo4j_data: